"""Run one composed regional-ecology world without a neural controller.

The fixture is generated by ``scripts/generate_regional_family.py``. Analyst
interventions in this script alter physical geometry and finite inventories;
they are never resident inputs or behavioral labels.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import math
import time
from collections import Counter
from pathlib import Path
from typing import Any

import mujoco
import numpy as np

from chreatures.biosphere import Biosphere
from chreatures.organism_interface import ACTION_NAMES
from chreatures.physical_batch import FastArticulatedSensoriumWorld


def _sha(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def _actions(world: Any, tick: int) -> dict[str, dict[str, float]]:
    result = {}
    for index, body in enumerate(world.bodies):
        phase = 0.041 * tick + 0.73 * index
        values = dict.fromkeys(ACTION_NAMES, 0.0)
        values.update(
            thrust=0.34 * math.sin(phase),
            yaw=0.22 * math.sin(phase * 0.61 + 0.4),
            gaze_pitch=0.18 * math.sin(phase * 0.37),
            posture=0.12 * math.cos(phase * 0.83),
            eat=0.20 if tick % 37 == index % 37 else 0.0,
            release=0.18 if tick % 43 == index % 43 else 0.0,
            secrete=0.16 if tick % 31 == index % 31 else 0.0,
            allocate=0.24 if tick % 29 == index % 29 else 0.0,
        )
        result[body.id] = values
    return result


def _regional_rows(regional: Any) -> np.ndarray:
    return np.asarray(regional._native.region_rows(), dtype=np.int64)


def _route_accessibility(regional: Any) -> np.ndarray:
    regional._ensure_physical()
    return np.asarray(
        regional._native.route_accessibility(
            int(regional.world.model._address),
            int(regional.world.data._address),
            regional._carrier_bodies,
        ),
        dtype=np.float64,
    )


def _set_free_position(world: Any, entity: str, position: list[float]) -> None:
    joint = world._entity_joint[entity]
    qpos = int(world.model.jnt_qposadr[joint])
    world.data.qpos[qpos : qpos + 3] = position
    world.data.qvel[int(world.model.jnt_dofadr[joint]) :][:6] = 0.0
    mujoco.mj_forward(world.model, world.data)
    world._sync_public_state()


def _obstruction_case(world: Any, biosphere: Biosphere, dt: float) -> dict[str, Any]:
    regional = biosphere.regional_matter
    assert regional is not None
    before = _route_accessibility(regional)
    changed = np.empty(0, dtype=np.int64)
    obstructed = before.copy()
    if np.any(before > 0.0):
        route = regional.config["routes"][int(np.argmax(before))]
        sample = route["clearance_samples"][0]
        pa = np.asarray(sample["from"], dtype=np.float64)
        pb = np.asarray(sample["to"], dtype=np.float64)
        midpoint = ((pa + pb) * 0.5).tolist()
        world.command(
            {
                "op": "add",
                "preset": "play-block",
                "id": "analyst-route-obstacle",
                "x": midpoint[0],
                "y": midpoint[1],
                "z": midpoint[2],
            }
        )
        obstructed = _route_accessibility(regional)
        changed = np.flatnonzero(obstructed < before)
        world.prepare_topology_batch(
            [{"op": "remove", "id": "analyst-route-obstacle"}]
        ).commit()
    if not changed.size:
        raise AssertionError("generated routes lack a physically open, obstructible corridor")
    if not np.array_equal(_route_accessibility(regional), before):
        raise AssertionError("removing the route obstacle failed to restore accessibility")

    outlet = regional.config["outlets"][0]
    obstacle_ids = []
    for index, item in enumerate(regional.config["outlets"]):
        obstacle_position = list(map(float, item["position"]))
        obstacle_id = f"analyst-outlet-obstacle-{index:02d}"
        obstacle_ids.append(obstacle_id)
        world.command(
            {
                "op": "add",
                "preset": "play-block",
                "id": obstacle_id,
                "x": obstacle_position[0],
                "y": obstacle_position[1],
                "z": obstacle_position[2],
            }
        )
    rows = _regional_rows(regional)
    outlet_region = next(
        item for item in regional.config["regions"] if item["id"] == outlet["region"]
    )
    receiver = int(outlet_region["row"])
    source = int(biosphere._mobile_specs[0]["body_row"])
    pool = int(np.argmax(biosphere.web.pools[source]))
    amount = min(0.02, float(biosphere.web.pools[source, pool]) * 0.25)
    if amount <= 0.0:
        raise AssertionError("fixture lacks finite material for outlet intervention")
    pool_name = biosphere.web.chemistry.pools[pool]
    biosphere.web.transfer(source, receiver, {pool_name: amount})
    regional_before = biosphere.web.pools[rows].sum(axis=0)
    slot = outlet["slots"][0]
    remaining = float(outlet["interval_s"])
    while remaining > 0.0:
        step = min(1.0, remaining)
        regional.after_reactions(step)
        remaining -= step
    regional_after = biosphere.web.pools[rows].sum(axis=0)
    if any(
        candidate in biosphere.materials.active_entities
        for item in regional.config["outlets"]
        for candidate in item["slots"]
    ):
        raise AssertionError("a physically obstructed outlet emitted a packet")
    if not np.allclose(regional_before, regional_after, rtol=0.0, atol=1e-12):
        raise AssertionError("blocked outlet changed total regional inventory")
    world.prepare_topology_batch(
        [{"op": "remove", "id": entity_id} for entity_id in obstacle_ids]
    ).commit()
    return {
        "route_intervention_feasible": bool(changed.size),
        "route_index": None if changed.size == 0 else int(changed[0]),
        "route_accessibility_before": None if changed.size == 0 else float(before[changed[0]]),
        "route_accessibility_obstructed": None if changed.size == 0 else float(obstructed[changed[0]]),
        "authored_routes_already_fully_obstructed": bool(np.all(before == 0.0)),
        "outlet": outlet["id"],
        "blocked_slot": slot,
        "retained_pool": pool_name,
        "retained_quantity": amount,
        "regional_inventory_exact": True,
    }


def _exit_case(world: Any, biosphere: Biosphere, dt: float) -> dict[str, Any]:
    regional = biosphere.regional_matter
    materials = biosphere.materials
    assert regional is not None and materials is not None
    outlet = regional.config["outlets"][0]
    outlet_region = next(
        item for item in regional.config["regions"] if item["id"] == outlet["region"]
    )
    slot = outlet["slots"][0]
    if slot in materials.active_entities:
        raise AssertionError("designated exit packet slot is already active")
    inside = list(map(float, outlet["position"]))
    # The preceding blocked interval earned release credit. Let the actual
    # network/outlet transaction emit its finite inventory at the authored pose.
    regional_before = biosphere.web.pools[_regional_rows(regional)].sum(axis=0)
    totals_before_release = biosphere.web.totals()
    before_packets = set(materials.active_free_entities)
    events = regional.after_reactions(dt)
    if slot not in materials.active_free_entities:
        raise AssertionError("scheduled finite outlet did not activate its physical packet")
    activated = set(materials.active_free_entities) - before_packets
    emitted = sum(
        (biosphere.web.pools[materials._item(entity)["row"]] for entity in activated),
        np.zeros(len(biosphere.web.chemistry.pools), dtype=np.float64),
    )
    regional_after = biosphere.web.pools[_regional_rows(regional)].sum(axis=0)
    if not np.allclose(regional_before - regional_after, emitted, rtol=0.0, atol=1e-12):
        raise AssertionError("outlet inventory was not debited from finite regional rows")
    packet_row = materials._item(slot)["row"]
    packet = biosphere.web.pools[packet_row].copy()
    if not np.any(packet > 0.0):
        raise AssertionError("scheduled outlet activated an empty packet")
    face = next(item for item in regional.config["exit_faces"] if item["axis"] == "x" and item["side"] == "max")
    target_region = next(item for item in regional.config["regions"] if item["id"] == face["region"])
    receiver = int(target_region["row"])
    receiver_before = biosphere.web.pools[receiver].copy()
    total_before = biosphere.web.totals()
    _set_free_position(world, slot, [float(face["coordinate_m"]) + 0.2, inside[1], inside[2]])
    events = regional.before_reactions(dt)
    if slot in world._entity_mj or slot in materials.active_entities:
        raise AssertionError("escaped packet remained physically active")
    if (
        not np.array_equal(biosphere.web.pools[receiver], receiver_before + packet)
        or np.any(biosphere.web.pools[packet_row] != 0.0)
        or len(events) != 1
        or events[0]["kind"] != "physical-material-entered-region"
        or events[0]["details"]["cause"] != "declared-world-face"
    ):
        raise AssertionError("escaped packet did not transfer completely into its region")
    total_after = biosphere.web.totals()
    residual = {
        name: total_after["elements"][name] - total_before["elements"][name]
        for name in total_before["elements"]
    }
    energy_residual = total_after["stored_energy"] - total_before["stored_energy"]
    if max(map(abs, residual.values())) > 1e-12 or abs(energy_residual) > 1e-12:
        raise AssertionError("physical exit changed conserved web inventory")
    return {
        "outlet": outlet["id"],
        "scheduled_outlet_activation": True,
        "activated_packets": sorted(activated),
        "regional_debit_matches_emission": True,
        "entity": slot,
        "face": face["id"],
        "cause": events[0]["details"]["cause"],
        "resources": dict(zip(biosphere.web.chemistry.pools, map(float, packet), strict=True)),
        "physical_entity_retired": True,
        "complete_inventory_transferred": True,
        "packet_row_empty": True,
        "elemental_residual": residual,
        "stored_energy_residual": energy_residual,
        "release_totals_before": totals_before_release,
    }


def _arguments() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument("--fixture", type=Path, required=True)
    parser.add_argument("--steps", type=int, default=1200)
    parser.add_argument("--continuation", type=int, default=12)
    parser.add_argument("--dt", type=float, default=0.05)
    parser.add_argument("--seed", type=int, default=2026090611)
    parser.add_argument("--output", type=Path, required=True)
    return parser.parse_args()


def main() -> None:
    args = _arguments()
    habitat_path = args.fixture / "habitat.json"
    biosphere_path = args.fixture / "biosphere.json"
    habitat = json.loads(habitat_path.read_text())
    world = FastArticulatedSensoriumWorld(seed=args.seed, spec=habitat)
    biosphere = Biosphere.from_config(world, biosphere_path)
    initial = biosphere.web.totals()
    initial_parts = len(biosphere.parts)
    obstruction = _obstruction_case(world, biosphere, args.dt)
    exit_case = _exit_case(world, biosphere, args.dt)
    regulation_before = np.asarray(
        biosphere.web._native.cumulative_regulation_atp, dtype=np.float64
    )
    event_counts: Counter[str] = Counter()
    started = time.perf_counter()
    for tick in range(args.steps):
        world.advance(_actions(world, tick), args.dt)
        biosphere.advance(args.dt)
        event_counts.update(event["kind"] for event in biosphere.last_report["evidence_events"])
        if (tick + 1) % 200 == 0:
            print(json.dumps({"tick": tick + 1, "seconds": time.perf_counter() - started, "parts": len(biosphere.parts)}), flush=True)
    regulation_after = np.asarray(
        biosphere.web._native.cumulative_regulation_atp, dtype=np.float64
    )
    world_snapshot = world.snapshot()
    biosphere_snapshot = biosphere.snapshot()
    checkpoint_path = args.output.with_suffix(".checkpoint.json")
    checkpoint_path.write_text(json.dumps({
        "format": "chreatures-regional-ecology-probe-checkpoint-v1",
        "completed_ticks": args.steps,
        "world": world_snapshot,
        "biosphere": biosphere_snapshot,
    }, sort_keys=True) + "\n")
    for tick in range(args.steps, args.steps + args.continuation):
        world.advance(_actions(world, tick), args.dt)
        biosphere.advance(args.dt)
    expected_world = world.snapshot()
    expected_biosphere = biosphere.snapshot()
    restored_world = FastArticulatedSensoriumWorld.restore(world_snapshot)
    restored_biosphere = Biosphere.restore(restored_world, biosphere_snapshot)
    for tick in range(args.steps, args.steps + args.continuation):
        restored_world.advance(_actions(restored_world, tick), args.dt)
        restored_biosphere.advance(args.dt)
    actual_world = restored_world.snapshot()
    actual_biosphere = restored_biosphere.snapshot()
    world_exact = expected_world == actual_world
    biosphere_exact = expected_biosphere == actual_biosphere
    if not world_exact or not biosphere_exact:
        raise AssertionError("regional ecology continuation differs after restore")
    accounting = biosphere.accounting()
    result = {
        "format": "chreatures-regional-ecology-probe-v2",
        "steps": args.steps,
        "continuation_steps": args.continuation,
        "dt_seconds": args.dt,
        "resident_count": len(world.bodies),
        "parts": len(biosphere.parts),
        "initial_parts": initial_parts,
        "event_counts": dict(event_counts),
        "elapsed_seconds": time.perf_counter() - started,
        "initial_totals": initial,
        "final_accounting": accounting,
        "regulation_atp_cost": float((regulation_after - regulation_before).sum()),
        "regulated_rows_changed": int(
            np.count_nonzero(
                np.any(
                    biosphere.web.enzyme_activity
                    != np.asarray(
                        [
                            [row["baseline"].get(name, 0.0) for name in biosphere.web.chemistry.reactions]
                            for row in biosphere_snapshot["web"]["regulation"]
                        ],
                        dtype=np.float64,
                    ),
                    axis=1,
                )
            )
        ),
        "obstruction": obstruction,
        "exit": exit_case,
        "world_restore_exact": world_exact,
        "biosphere_restore_exact": biosphere_exact,
        "checkpoint": {"path": str(checkpoint_path.resolve()), "sha256": _sha(checkpoint_path)},
        "native": {
            "path": str(Path(__import__("_world_kernels").__file__).resolve()),
            "sha256": _sha(Path(__import__("_world_kernels").__file__).resolve()),
        },
        "source_sha256": {
            str(habitat_path): _sha(habitat_path),
            str(biosphere_path): _sha(biosphere_path),
            str(Path(__file__).resolve()): _sha(Path(__file__).resolve()),
        },
    }
    args.output.write_text(json.dumps(result, indent=2, sort_keys=True) + "\n")
    print(json.dumps(result, sort_keys=True))


if __name__ == "__main__":
    main()
