const $ = id => document.getElementById(id);
const canvas = $('world'), ctx = canvas.getContext('2d');
let state=null, selected='mica', tool='hand', showScents=false, showTrails=true, showSight=false, activeTab='resident';
let scale=1, ox=0, oy=0, width=1000, height=800, lastFrame=0, connectome=null, pointer={x:600,y:400}, drag=null;
let selectedTone=0, toastTimer, connectionAttempt=0, lastJournalKey='', frames=0;
const colors=['#ef8e9c','#e9c279','#b598dc'];
const clamp=(x,a,b)=>Math.max(a,Math.min(b,x));
const timeLabel=t=>`${Math.floor(t/60).toString().padStart(2,'0')}:${Math.floor(t%60).toString().padStart(2,'0')}`;
function toast(message,error=false){$('toast').textContent=message;$('toast').classList.toggle('error',error);$('toast').classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.remove('visible'),3500);}
async function command(value){try{const r=await fetch('/api/command',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(value)});const data=await r.json();if(!r.ok)throw Error(data.detail||'Could not apply that action');return data;}catch(e){toast(e.message,true);return null;}}
function selectTool(value){tool=value;document.querySelectorAll('[data-tool]').forEach(b=>b.classList.toggle('selected',b.dataset.tool===value));const hints={hand:'Click a resident to watch. Drag an object to move it.',food0:'Place a berry patch. Its scent travels through the garden.',food1:'Place nectar. Food is learned through encounters.',toy:'Place a scented ball. Bodies can push it around.',flower:'Place a flower with a different scent.',shelter:'Place shelter. Its shade is something they can sense.',tone:'Click to sing. A / S / D play three different notes.'};$('instruction').textContent=hints[value];canvas.style.cursor=value==='hand'?'grab':'crosshair';}
document.querySelectorAll('[data-tool]').forEach(b=>b.onclick=()=>selectTool(b.dataset.tool));
document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{activeTab=b.dataset.tab;document.querySelectorAll('[data-tab]').forEach(x=>x.classList.toggle('active',x===b));['resident','journal','circuit'].forEach(x=>$(x+'-panel').classList.toggle('hidden',x!==activeTab));});
$('pause').onclick=()=>state&&command({op:'pause',paused:!state.paused});
$('speed').onclick=()=>state&&command({op:'speed',value:{1:2,2:4,4:1}[state.speed]});
$('save').onclick=async()=>{if(await command({op:'save'}))toast('Neural state, memories, body and world saved.');};
for(const [id,setter] of [['scents',()=>showScents=!showScents],['trails',()=>showTrails=!showTrails],['sight',()=>showSight=!showSight]])$(id).onclick=()=>$(id).classList.toggle('active',setter());
function coordinates(event){const r=canvas.getBoundingClientRect();return {x:clamp((event.clientX-r.left-ox)/scale,0,state?.width||1200),y:clamp((event.clientY-r.top-oy)/scale,0,state?.height||800)};}
canvas.addEventListener('pointermove',e=>{pointer=coordinates(e);if(drag){drag.x=pointer.x;drag.y=pointer.y;}});
canvas.addEventListener('pointerdown',e=>{if(!state)return;pointer=coordinates(e);canvas.focus();if(tool==='hand'){const b=state.bodies.find(b=>Math.hypot(b.x-pointer.x,b.y-pointer.y)<23);if(b){selected=b.id;updateInspector();return;}const o=[...state.objects].reverse().find(o=>Math.hypot(o.x-pointer.x,o.y-pointer.y)<o.radius+8);if(o){drag={id:o.id,x:o.x,y:o.y};canvas.setPointerCapture(e.pointerId);}}else place();});
canvas.addEventListener('pointerup',async()=>{if(drag){const d=drag;drag=null;await command({op:'move',id:d.id,x:d.x,y:d.y});}});
canvas.addEventListener('pointercancel',()=>drag=null);
function place(){const {x,y}=pointer;if(tool==='tone'){command({op:'signal',x,y,tone:selectedTone});playTone(selectedTone);return;}const config={food0:{kind:'food',odor:0,color:colors[0]},food1:{kind:'food',odor:1,color:colors[1]},toy:{kind:'toy',odor:2,color:colors[2]},flower:{kind:'flower',odor:2,color:'#b38cbd'},shelter:{kind:'shelter'}}[tool];if(config)command({op:'add',x,y,...config});}
let audioContext;
function playTone(tone){try{audioContext??=new AudioContext();const o=audioContext.createOscillator(),g=audioContext.createGain();o.type='sine';o.frequency.value=[261.63,329.63,392][tone];g.gain.setValueAtTime(.055,audioContext.currentTime);g.gain.exponentialRampToValueAtTime(.001,audioContext.currentTime+.38);o.connect(g).connect(audioContext.destination);o.start();o.stop(audioContext.currentTime+.4);}catch{}}
window.addEventListener('keydown',e=>{if(e.target.tagName==='INPUT'||e.ctrlKey||e.metaKey||e.altKey)return;if(e.code==='Space'){e.preventDefault();$('pause').click();}if('1234567'.includes(e.key))selectTool(['hand','food0','food1','toy','flower','shelter','tone'][+e.key-1]);if('asd'.includes(e.key.toLowerCase())){selectedTone='asd'.indexOf(e.key.toLowerCase());const b=state?.bodies.find(x=>x.id===selected);if(b){command({op:'signal',x:pointer.x,y:pointer.y,tone:selectedTone});playTone(selectedTone);}}});
function resize(){const r=canvas.getBoundingClientRect(),dpr=Math.min(window.devicePixelRatio||1,2);width=r.width;height=r.height;canvas.width=width*dpr;canvas.height=height*dpr;ctx.setTransform(dpr,0,0,dpr,0,0);scale=Math.min((width-64)/1200,(height-155)/800);ox=(width-1200*scale)/2;oy=(height-800*scale)/2-12;}
new ResizeObserver(resize).observe(canvas);
function ellipse(c,x,y,rx,ry,color,angle=0){c.beginPath();c.ellipse(x,y,rx,ry,angle,0,Math.PI*2);c.fillStyle=color;c.fill();}
function path(c,pts,color,line=1){c.beginPath();pts.forEach((p,i)=>i?c.lineTo(...p):c.moveTo(...p));c.strokeStyle=color;c.lineWidth=line;c.stroke();}
function drawCreature(c,b,t,large=false){c.save();c.translate(b.x,b.y);c.rotate(b.heading);const r=b.radius||9, gait=t*Math.max(0,b.speed||0)*.16;c.lineCap='round';
 for(let side of [-1,1])for(let leg=0;leg<3;leg++){const phase=gait+leg*2.25+(side===1?Math.PI:0),swing=Math.sin(phase)*3.1;const x=6-leg*6;path(c,[[x,side*r*.45],[x-3+swing,side*(r+4)],[x-7+swing*1.4,side*(r+10)]],b.color+'bf',1.5);}
 ellipse(c,-5,3,15,9,'#00000028');const grad=c.createLinearGradient(-15,0,14,0);grad.addColorStop(0,b.color+'a0');grad.addColorStop(.65,b.color);grad.addColorStop(1,'#d2d9ac');ellipse(c,-5,0,r*1.5,r*.83,grad);ellipse(c,5,0,r*.9,r*.83,b.color);ellipse(c,12,0,r*.58,r*.68,b.color);
 for(let i=0;i<3;i++)path(c,[[-6-i*4,-r*.67],[-7-i*4,0],[-6-i*4,r*.67]],'#132a2d60',1);
 for(let side of [-1,1]){const wiggle=Math.sin(t*2+side)*1.5;path(c,[[14,side*4],[23,side*(9+wiggle)],[29,side*(10+wiggle)]],b.color+'c9',1.2);ellipse(c,29,side*(10+wiggle),1.9,1.9,'#d4e4b9');ellipse(c,14,side*4.4,2.2,2.2,'#0a2228');ellipse(c,14.5,side*4.1,.7,.7,'#d4e4b9');}
 c.restore();}
const stones=new Map();
function drawObject(o,t){const c=ctx, x=drag?.id===o.id?drag.x:o.x,y=drag?.id===o.id?drag.y:o.y,r=o.radius;
 if(o.kind==='food'&&o.amount<=0.005){ellipse(c,x,y,Math.max(3,r*.5),r*.35,'#46524655');return;}
 c.save();c.translate(x,y);
 if(o.kind==='shelter'){const g=c.createRadialGradient(0,0,0,0,0,r*1.25);g.addColorStop(0,'#060f17ba');g.addColorStop(.78,'#08192099');g.addColorStop(1,'#11242b00');ellipse(c,0,0,r*1.25,r*1.25,g);c.strokeStyle='#63827535';c.lineWidth=1;c.setLineDash([3,8]);c.beginPath();c.arc(0,0,r,0,Math.PI*2);c.stroke();c.setLineDash([]);for(let i=0;i<7;i++){const a=Math.PI*1.05+i*.34;ellipse(c,Math.cos(a)*r*.83,Math.sin(a)*r*.75,23,10,'#35584f',a+1);path(c,[[Math.cos(a)*r*.61,Math.sin(a)*r*.56],[Math.cos(a)*r*.95,Math.sin(a)*r*.86]],'#78947355');}}
 else if(o.kind==='stone'){ellipse(c,5,8,r*1.02,r*.90,'#00000030');c.beginPath();for(let i=0;i<9;i++){const a=i/9*Math.PI*2,q=r*(.87+.12*Math.sin(i*2.32+r));i?c.lineTo(Math.cos(a)*q,Math.sin(a)*q):c.moveTo(Math.cos(a)*q,Math.sin(a)*q);}c.closePath();const g=c.createLinearGradient(-r,-r,r,r);g.addColorStop(0,o.color);g.addColorStop(1,'#293f48');c.fillStyle=g;c.fill();c.strokeStyle='#b1c4b623';c.stroke();path(c,[[-r*.5,-r*.45],[r*.05,-r*.64],[r*.45,-r*.32]],'#c3d4c431',2);}
 else if(o.kind==='food'){const a=clamp(o.amount,0,1),g=c.createRadialGradient(0,0,0,0,0,r*3.6);g.addColorStop(0,o.color+'28');g.addColorStop(1,o.color+'00');ellipse(c,0,0,r*3.6,r*3.6,g);for(let i=0;i<5;i++){const angle=i*2.4,rr=r*(.25+.27*(i%2)),px=Math.cos(angle)*rr,py=Math.sin(angle)*rr;ellipse(c,px+1,py+2,r*.46,r*.41,'#00000025');ellipse(c,px,py,r*(.27+.2*a),r*(.27+.2*a),o.color);ellipse(c,px-1,py-2,1.4,1.1,'#fff3d352');}}
 else if(o.kind==='toy'){ellipse(c,3,4,r,r,'#00000035');const g=c.createRadialGradient(-r*.35,-r*.35,1,0,0,r);g.addColorStop(0,'#d5c5e2');g.addColorStop(.28,o.color);g.addColorStop(1,'#645581');ellipse(c,0,0,r,r,g);c.beginPath();c.ellipse(0,0,r*.80,r*.37,.8,0,Math.PI*2);c.strokeStyle='#e7ddef44';c.stroke();}
 else if(o.kind==='flower'){for(let i=0;i<6;i++){const a=i*Math.PI/3+t*.02;ellipse(c,Math.cos(a)*r*.53,Math.sin(a)*r*.53,r*.56,r*.28,o.color+'b0',a);}ellipse(c,0,0,r*.27,r*.27,'#d5d897');}
 else if(o.kind==='beacon'){const g=c.createRadialGradient(0,0,2,0,0,45);g.addColorStop(0,o.color+'23');g.addColorStop(1,o.color+'00');ellipse(c,0,0,45,45,g);ellipse(c,0,0,r,r,'#25505b');ellipse(c,0,-2,r*.48,r*.48,o.color);for(let i=0;i<2;i++){const rr=r+((t*12+i*14)%30);c.beginPath();c.arc(0,0,rr,0,Math.PI*2);c.strokeStyle=o.color+Math.round((1-(rr-r)/30)*45).toString(16).padStart(2,'0');c.lineWidth=1;c.stroke();}}
 c.restore();}
function draw(now){requestAnimationFrame(draw);if(!state)return;const t=state.time+(state.paused?0:Math.min(.1,(now-lastFrame)/1000));ctx.clearRect(0,0,width,height);const g=ctx.createRadialGradient(width*.43,height*.41,15,width*.45,height*.47,width*.76);g.addColorStop(0,'#183137');g.addColorStop(1,'#101c25');ctx.fillStyle=g;ctx.fillRect(0,0,width,height);ctx.save();ctx.translate(ox,oy);ctx.scale(scale,scale);
 // A coordinate-grounded floor texture, stable across reloads.
 for(let i=0;i<500;i++){const x=(Math.sin(i*313.31)*10000%1+1)%1*1200,y=(Math.sin(i*127.77+7)*10000%1+1)%1*800;ellipse(ctx,x,y,i%7===0?1.5:.7,.7,i%3===0?'#a7bc9021':'#63817522',i);}
 ctx.strokeStyle='#71948022';ctx.lineWidth=1;ctx.beginPath();ctx.roundRect(0,0,1200,800,20);ctx.stroke();
 if(showScents)for(const o of state.objects){if(o.odor===null||o.odor===undefined||o.amount<=0)continue;const g=ctx.createRadialGradient(o.x,o.y,0,o.x,o.y,240);g.addColorStop(0,colors[o.odor]+'35');g.addColorStop(.38,colors[o.odor]+'13');g.addColorStop(1,colors[o.odor]+'00');ctx.fillStyle=g;ctx.fillRect(o.x-240,o.y-240,480,480);}
 if(showTrails)for(const b of state.bodies){const h=state.history[b.id]||[];if(h.length>1){ctx.beginPath();h.forEach((p,i)=>i?ctx.lineTo(p.x,p.y):ctx.moveTo(p.x,p.y));ctx.strokeStyle=b.color+'36';ctx.lineWidth=1.4;ctx.stroke();}}
 for(const o of state.objects.filter(o=>o.kind==='shelter'))drawObject(o,t);
 if(showSight){const b=state.bodies.find(b=>b.id===selected),v=state.senses[selected]?.vision;if(b&&v){for(let i=0;i<16;i++){const a=b.heading+(-75+i*10)*Math.PI/180,dist=260*(1-v[i][3]);path(ctx,[[b.x,b.y],[b.x+Math.cos(a)*dist,b.y+Math.sin(a)*dist]],b.color+'21',1);}}}
 for(const o of state.objects.filter(o=>o.kind!=='shelter'))drawObject(o,t);
 for(const s of state.signals){const r=(1.25-s.remaining)*105+12;ctx.beginPath();ctx.arc(s.x,s.y,r,0,Math.PI*2);ctx.strokeStyle=['#9edcca','#dbcb86','#c5a9df'][s.tone]+Math.round(clamp(s.remaining/1.25,0,1)*65).toString(16).padStart(2,'0');ctx.lineWidth=1.4;ctx.stroke();}
 for(const b of state.bodies){if(b.id===selected){ctx.beginPath();ctx.arc(b.x,b.y,30,0,Math.PI*2);ctx.strokeStyle=b.color+'65';ctx.lineWidth=.9;ctx.stroke();}drawCreature(ctx,b,t);ctx.font='12px "DM Sans",sans-serif';ctx.textAlign='center';ctx.fillStyle=b.id===selected?'#e0e8d6':'#a9bab0';ctx.fillText(b.name,b.x,b.y+43);}
 if(tool!=='hand'){ctx.beginPath();ctx.arc(pointer.x,pointer.y,tool==='shelter'?72:tool==='tone'?22:13,0,Math.PI*2);ctx.strokeStyle='#deebba99';ctx.setLineDash([3,4]);ctx.lineWidth=1;ctx.stroke();ctx.setLineDash([]);}
 ctx.restore();if(++frames%3===0)drawInspector(t);}
function updateInspector(){if(!state)return;const b=state.bodies.find(b=>b.id===selected),brain=state.brains[selected];if(!b||!brain)return;
 if(!$('residents').children.length){for(const b of state.bodies){const button=document.createElement('button');button.dataset.id=b.id;const dot=document.createElement('i');dot.style.background=b.color;button.append(dot,document.createTextNode(b.name));button.onclick=()=>{selected=b.id;updateInspector();};$('residents').append(button);}}
 for(const button of $('residents').children)button.classList.toggle('active',button.dataset.id===selected);
 $('name').textContent=b.name;$('mode').textContent=brain.mode;$('age').textContent=`${timeLabel(b.age)} in this world`;
 for(const k of ['energy','gut','fatigue']){$(k).style.width=(b[k]*100)+'%';$(k+'-label').textContent=Math.round(b[k]*100)+'%';}
 $('episode-count').textContent=`${brain.episodes} encounters`;$('activity-label').textContent=brain.activity.toFixed(3);
 if(!$('associations').children.length){for(let i=0;i<3;i++){const div=document.createElement('div');div.className='association';div.innerHTML=`<span class="cue">${['Berry','Nectar','Floral'][i]}</span><span class="weight"><i style="background:${colors[i]}"></i></span><span class="value"></span>`;$('associations').append(div);}}
 [...$('associations').children].forEach((el,i)=>{el.querySelector('i').style.width=brain.values[i]*100+'%';el.querySelector('.value').textContent=brain.values[i].toFixed(2);});
 const a=state.senses[selected].odor;$('antennae').replaceChildren();for(let side=0;side<2;side++){const div=document.createElement('div');div.innerHTML=`<div class="antenna-label">${side===0?'LEFT':'RIGHT'} ANTENNA</div><div class="antenna-bars"></div>`;for(let i=0;i<3;i++){const bar=document.createElement('i');bar.style.background=colors[i];bar.style.height=(2+clamp(a[side][i],0,1)*11)+'px';bar.title=`${['Berry','Nectar','Floral'][i]} ${a[side][i].toFixed(3)}`;div.querySelector('.antenna-bars').append(bar);}$('antennae').append(div);}
 const key=JSON.stringify(state.journal.map(e=>e.id));if(key!==lastJournalKey){lastJournalKey=key;$('journal').replaceChildren();for(const e of [...state.journal].reverse()){const div=document.createElement('div');div.className='journal-entry';const tm=document.createElement('time');tm.textContent=timeLabel(e.time);const p=document.createElement('p');p.textContent=e.text;div.append(tm,p);$('journal').append(div);}}
 $('clock').textContent=timeLabel(state.time);$('pause').textContent=state.paused?'▷ Resume':'Ⅱ Pause';$('pause').setAttribute('aria-label',state.paused?'Resume simulation':'Pause simulation');$('speed').textContent=state.speed+'×';$('performance').textContent=`${state.performance.step_ms.toFixed(1)} ms / step`;$('world-state').textContent=state.paused?'World paused':state.saved_at?'Life saved automatically':'A shared, persistent world';}
function drawInspector(t){if(!state)return;const b=state.bodies.find(b=>b.id===selected),brain=state.brains[selected];if(!b||!brain)return;if(activeTab==='resident'){
 const p=$('portrait').getContext('2d');p.clearRect(0,0,300,135);p.save();p.translate(155,65);p.scale(2.05,2.05);drawCreature(p,{...b,x:0,y:0,heading:-.15},t);p.restore();
 const r=$('retina').getContext('2d'),v=state.senses[selected].vision;r.clearRect(0,0,300,62);v.forEach((ray,i)=>{const rgb=ray.slice(0,3).map(x=>Math.round(x*255));r.fillStyle=`rgb(${rgb.join(',')})`;r.fillRect(i*300/16+1,2,300/16-2,42);r.fillStyle='#bfcfac';r.fillRect(i*300/16+2,58-ray[3]*10,300/16-4,ray[3]*10+1);});
 const c=$('sparkline').getContext('2d'),h=state.history[selected]||[];c.clearRect(0,0,300,64);if(h.length>1){const min=Math.min(...h.map(x=>x.activity))*.9,max=Math.max(...h.map(x=>x.activity))+.001;path(c,h.map((x,i)=>[i/(h.length-1)*300,58-(x.activity-min)/(max-min)*47]),b.color,1.3);}}
 if(activeTab==='circuit'){const c=$('neural-map').getContext('2d');c.clearRect(0,0,300,270);const n=brain.neural.rates.length;for(let i=0;i<n;i++){const angle=i*2.39996,rad=Math.sqrt(i/n)*114,x=150+Math.cos(angle)*rad,y=134+Math.sin(angle)*rad;const a=brain.neural.rates[i],v=clamp(a*5,0,1);ellipse(c,x,y,1.8+v*2.4,1.8+v*2.4,`rgba(${Math.round(95+v*125)},${Math.round(140+v*70)},${Math.round(151-v*15)},${.3+v*.7})`);}}
}
async function loadMetadata(){try{const r=await fetch('/api/connectome');if(!r.ok)throw Error('Circuit loading');connectome=await r.json();$('anatomy').textContent=`FlyWire v783 · female brain subset · ${connectome.neurons.toLocaleString()} neurons`;
 const fields=[['Neurons',connectome.neurons.toLocaleString()],['Directed connections',connectome.connections.toLocaleString()],['Synapses represented',connectome.synapses.toLocaleString()],['Sensory cells',connectome.input_cells.toLocaleString()],['Readout cells',connectome.readout_cells.toLocaleString()],['Dynamics','Adaptive rates'],['Anatomy','FlyWire v783']];for(const[k,v]of fields){const dt=document.createElement('dt'),dd=document.createElement('dd');dt.textContent=k;dd.textContent=v;$('circuit-stats').append(dt,dd);}}catch{setTimeout(loadMetadata,2500);}}
function connect(){const ws=new WebSocket(`${location.protocol==='https:'?'wss':'ws'}://${location.host}/ws`);ws.onopen=()=>{connectionAttempt=0;$('connection').textContent='● live';$('connection').classList.add('online');};ws.onmessage=e=>{const next=JSON.parse(e.data);if(!next.bodies){$('anatomy').textContent=next.error||'Starting…';return;}state=next;lastFrame=performance.now();updateInspector();if(next.error)toast(next.error,true);};ws.onclose=()=>{$('connection').textContent='reconnecting';$('connection').classList.remove('online');setTimeout(connect,Math.min(5000,500+connectionAttempt++*600));};ws.onerror=()=>ws.close();}
loadMetadata();connect();requestAnimationFrame(draw);
