import * as THREE from 'three';
import {OrbitControls} from './vendor/three/OrbitControls.js';
const $=id=>document.getElementById(id), canvas=$('world3d');
const renderer=new THREE.WebGLRenderer({canvas,antialias:true,alpha:false});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.3;
const scene=new THREE.Scene();scene.background=new THREE.Color('#17292d');scene.fog=new THREE.FogExp2('#17292d',.023);
const camera=new THREE.PerspectiveCamera(39,1,.025,120);camera.up.set(0,0,1);camera.position.set(17,-13,16);
const controls=new OrbitControls(camera,canvas);controls.target.set(6,4,.2);controls.enableDamping=true;controls.dampingFactor=.08;controls.minDistance=.5;controls.maxDistance=33;controls.maxPolarAngle=Math.PI*.48;
scene.add(new THREE.HemisphereLight('#e8ead1','#33443b',2));const sun=new THREE.DirectionalLight('#ffe7b3',3.2);sun.position.set(2,-3,15);sun.target.position.set(6,4,0);scene.add(sun,sun.target);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);Object.assign(sun.shadow.camera,{left:-11,right:11,top:10,bottom:-10,near:.5,far:40});sun.shadow.normalBias=.025;sun.shadow.bias=-.00015;
const fill=new THREE.DirectionalLight('#8ebed0',1.4);fill.position.set(12,9,7);scene.add(fill);
const sceneLight=new THREE.PointLight('#d4efbf',0,9,1);scene.add(sceneLight);
const objects=new Map(), bodies=new Map(), ray=new THREE.Raycaster(), mouse=new THREE.Vector2(), groundPlane=new THREE.Plane(new THREE.Vector3(0,0,1),0), cursor=new THREE.Vector3(6,4,0);
let state=null, selected='mica', tool='hand', cameraMode='overview', drag=null, lastDragSend=0, dragBusy=false, lastReceived=0, toastTimeout, journalKey='', signals=[];
const clamp=(x,a,b)=>Math.max(a,Math.min(b,x));const clock=t=>`${Math.floor(t/60).toString().padStart(2,'0')}:${Math.floor(t%60).toString().padStart(2,'0')}`;
const quat=q=>new THREE.Quaternion(q[1],q[2],q[3],q[0]);
function toast(message,error=false){$('toast').textContent=message;$('toast').classList.toggle('error',error);$('toast').classList.add('visible');clearTimeout(toastTimeout);toastTimeout=setTimeout(()=>$('toast').classList.remove('visible'),3500);}
async function command(data){try{const r=await fetch('/api/command',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});const d=await r.json();if(!r.ok)throw Error(d.detail||'Interaction rejected');return d;}catch(e){toast(e.message,true);return null;}}
const geometries=new Map();function shapeGeometry(type,size){const key=type+JSON.stringify(size);if(geometries.has(key))return geometries.get(key);let g;if(type==='box')g=new THREE.BoxGeometry(size[0]*2,size[1]*2,size[2]*2);else if(type==='sphere')g=new THREE.SphereGeometry(size[0],24,16);else if(type==='ellipsoid'){g=new THREE.SphereGeometry(1,28,18);g.scale(...size);}else if(type==='cylinder'){g=new THREE.CylinderGeometry(size[0],size[0],size[1]*2,24);g.rotateX(Math.PI/2);}else if(type==='capsule'){g=new THREE.CapsuleGeometry(size[0],size[1]*2,6,16);g.rotateX(Math.PI/2);}else g=new THREE.BoxGeometry(.1,.1,.1);geometries.set(key,g);return g;}
function makeMesh(type,size,color,roughness=.85){const m=new THREE.Mesh(shapeGeometry(type,size),new THREE.MeshStandardMaterial({color,roughness,metalness:.025}));m.castShadow=true;m.receiveShadow=true;scene.add(m);return m;}
function label(text,color){const c=document.createElement('canvas');c.width=256;c.height=64;const x=c.getContext('2d');x.font='500 26px system-ui';x.textAlign='center';x.fillStyle=color;x.fillText(text,128,39);const sprite=new THREE.Sprite(new THREE.SpriteMaterial({map:new THREE.CanvasTexture(c),transparent:true,depthTest:false}));sprite.scale.set(.70,.175,1);return sprite;}
const selectRing=new THREE.Mesh(new THREE.RingGeometry(.155,.164,48),new THREE.MeshBasicMaterial({color:'#ddeb9d',side:THREE.DoubleSide,transparent:true,opacity:.8}));scene.add(selectRing);
const handMesh=new THREE.Mesh(new THREE.SphereGeometry(.07,16,12),new THREE.MeshPhysicalMaterial({color:'#e4dfa9',roughness:.12,metalness:.05,transparent:true,opacity:.65}));scene.add(handMesh);handMesh.visible=false;
function updateScene(){if(!state)return;const alive=new Set();for(const e of state.entities){e.shapes.forEach((s,i)=>{const id=e.id+':'+i;alive.add(id);let m=objects.get(id);if(!m){m=makeMesh(s.type,s.size,s.color,e.physical_material==='timber'?.7:.90);m.userData={id:e.id,mobility:e.mobility,type:'object'};objects.set(id,m);}m.userData.target=new THREE.Vector3(...s.position);m.userData.rotation=quat(s.quaternion);if(!m.userData.initialized){m.position.copy(m.userData.target);m.quaternion.copy(m.userData.rotation);m.userData.initialized=true;}m.material.color.set(s.color);if(e.id.endsWith('wall')){m.material.transparent=true;m.material.opacity=.32;m.castShadow=false;}});}for(const[id,m]of objects)if(!alive.has(id)){scene.remove(m);m.material.dispose();objects.delete(id);}
 for(const b of state.bodies){let m=bodies.get(b.id);if(!m){m=makeMesh(b.shape,b.size,b.color,.42);m.userData={id:b.id,type:'resident'};const l=label(b.name,'#e7eccf');l.position.z=.22;m.add(l);bodies.set(b.id,m);}m.userData.target=new THREE.Vector3(b.x,b.y,b.z);m.userData.rotation=quat(b.quaternion);if(!m.userData.initialized){m.position.copy(m.userData.target);m.quaternion.copy(m.userData.rotation);m.userData.initialized=true;}}
 if(state.hand){handMesh.visible=true;handMesh.position.fromArray(state.hand.target);}else handMesh.visible=false;
 if(state.light){sceneLight.position.fromArray(state.light.position||state.light.target||[6,4,2]);sceneLight.intensity=(state.light.intensity||0)*10;}else sceneLight.intensity=0;
 for(const s of signals)scene.remove(s);signals=[];for(const s of (state.signals||[]).slice(-30)){const radius=Math.max(.03,(1.25-s.remaining)*.85);const m=new THREE.Mesh(new THREE.RingGeometry(radius,radius+.006,48),new THREE.MeshBasicMaterial({color:['#a0d4c1','#e8d082','#bd9bd3'][s.tone],transparent:true,opacity:clamp(s.remaining/1.25,0,.55),side:THREE.DoubleSide,depthWrite:false}));m.position.set(s.x,s.y,s.z+.015);scene.add(m);signals.push(m);}}
function pointer(e){const r=canvas.getBoundingClientRect();mouse.set((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1);ray.setFromCamera(mouse,camera);const p=ray.ray.intersectPlane(drag?new THREE.Plane(new THREE.Vector3(0,0,1),-drag.height):groundPlane,new THREE.Vector3());if(p)cursor.copy(p);}
function hits(){return ray.intersectObjects([...objects.values(),...bodies.values()],false);}
canvas.addEventListener('pointerdown',e=>{if(e.button!==0||!state)return;pointer(e);const hit=hits()[0];if(tool==='hand'){if(hit?.object.userData.type==='resident'){selected=hit.object.userData.id;updatePanel();return;}if(hit?.object.userData.mobility==='free'){const id=hit.object.userData.id,entity=state.entities.find(x=>x.id===id);drag={id,height:Math.max(.1,entity.z+.25)};controls.enabled=false;cursor.set(entity.x,entity.y,drag.height);command({op:'hand',id,x:cursor.x,y:cursor.y,z:cursor.z});canvas.setPointerCapture(e.pointerId);}}else{controls.enabled=false;const p=hit?.point||cursor;if(tool==='tone')sing(0,p);else if(tool==='light')command({op:'light',x:p.x,y:p.y,z:Math.max(.2,p.z+1.5),intensity:.8,duration:12});else command({op:'add',preset:tool,x:clamp(p.x,0,12),y:clamp(p.y,0,8),z:Math.max(.25,p.z+.4)});}});
canvas.addEventListener('pointermove',e=>{pointer(e);if(drag&&performance.now()-lastDragSend>70&&!dragBusy){lastDragSend=performance.now();dragBusy=true;command({op:'hand',id:drag.id,x:clamp(cursor.x,0,12),y:clamp(cursor.y,0,8),z:drag.height}).finally(()=>dragBusy=false);}});
function release(){if(drag){drag=null;command({op:'release'});}controls.enabled=cameraMode==='overview';}canvas.addEventListener('pointerup',release);canvas.addEventListener('pointercancel',release);
canvas.addEventListener('wheel',e=>{if(drag){e.preventDefault();e.stopImmediatePropagation();drag.height=clamp(drag.height-e.deltaY*.003,.12,3.3);command({op:'hand',id:drag.id,x:clamp(cursor.x,0,12),y:clamp(cursor.y,0,8),z:drag.height});}}, {capture:true,passive:false});
let audio;function sing(tone,p=cursor){command({op:'signal',x:clamp(p.x,0,12),y:clamp(p.y,0,8),z:Math.max(.12,p.z),tone});try{audio??=new AudioContext();const o=audio.createOscillator(),g=audio.createGain();o.frequency.value=[261.63,329.63,392][tone];g.gain.setValueAtTime(.05,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+.4);o.connect(g).connect(audio.destination);o.start();o.stop(audio.currentTime+.45);}catch{}}
function setTool(t){tool=t;document.querySelectorAll('[data-tool]').forEach(b=>b.classList.toggle('selected',b.dataset.tool===t));$('instruction').textContent={hand:'Drag an object to hold it. Scroll while holding to lift or lower.',berry:'Offer food by dropping it onto the physical world.',nectar:'Place nectar. Gravity and contact determine where it goes.',ball:'A scented, resonant ball to move and investigate.',box:'A block to stack, push, or change a path.',light:'Cast a temporary light into the garden.',tone:'Click to sing. A / S / D play three different notes.'}[t];controls.enableRotate=t==='hand';}
document.querySelectorAll('[data-tool]').forEach(b=>b.onclick=()=>setTool(b.dataset.tool));
for(const mode of ['overview','follow','eyes'])$(mode).onclick=()=>{cameraMode=mode;controls.enabled=mode==='overview';['overview','follow','eyes'].forEach(x=>$(x).classList.toggle('active',x===mode));if(mode==='overview'){camera.position.set(17,-13,16);controls.target.set(6,4,.2);controls.update();}};
document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-tab]').forEach(x=>x.classList.toggle('active',x===b));['resident','journal','body'].forEach(x=>$(x+'-panel').classList.toggle('hidden',x!==b.dataset.tab));});
$('pause').onclick=()=>state&&command({op:'pause',paused:!state.paused});$('speed').onclick=()=>state&&command({op:'speed',value:{1:2,2:4,4:1}[state.speed]});$('save').onclick=async()=>{if(await command({op:'save'}))toast('Physical world, full neural state and personal memory saved.');};$('bookmark').onclick=async()=>{if(await command({op:'bookmark',text:$('note-text').value||'A moment in the garden.'})){toast('Observation attached to this moment.');$('note-text').value='';}};
window.addEventListener('keydown',e=>{if(['INPUT','TEXTAREA'].includes(e.target.tagName)||e.ctrlKey||e.metaKey||e.altKey)return;if(e.code==='Space'){e.preventDefault();$('pause').click();}if(['a','s','d'].includes(e.key.toLowerCase()))sing(['a','s','d'].indexOf(e.key.toLowerCase()));if(['1','2','3','4','5','6','7'].includes(e.key))setTool(['hand','berry','nectar','ball','box','light','tone'][+e.key-1]);});
function updatePanel(){const b=state.bodies.find(x=>x.id===selected),c=state.cognition[selected],n=state.neural[selected];if(!b||!c)return;if(!$('residents').children.length)for(const body of state.bodies){const button=document.createElement('button'),dot=document.createElement('i');dot.style.background=body.color;button.append(dot,document.createTextNode(body.name));button.dataset.id=body.id;button.onclick=()=>{selected=body.id;updatePanel();};$('residents').append(button);}for(const el of $('residents').children)el.classList.toggle('active',el.dataset.id===selected);$('name').textContent=b.name;
 for(const k of ['energy','gut','fatigue']){$(k).style.width=b[k]*100+'%';$(k+'-label').textContent=Math.round(b[k]*100)+'%';}
 $('clock').textContent=clock(state.time);$('age').textContent=clock(b.age);$('pause').textContent=state.paused?'▷ Resume':'Ⅱ Pause';$('speed').textContent=state.speed+'×';$('memory-count').textContent=c.memory_count+' encounters';$('activity').textContent=n.activity.toFixed(4);$('prediction').textContent=c.metrics.prediction_error.toFixed(4);$('progress').textContent=c.metrics.learning_progress.toFixed(5);$('performance').textContent=`${state.performance.step_ms.toFixed(1)} ms / step · full brain + cord`;$('physics-engine').textContent=state.engine.name+' '+state.engine.version;$('world-state').textContent=state.paused?'World paused':state.saved_at?'Whole world saved automatically':'Three lives in one physical world';
 if(!$('context-map').children.length)for(let i=0;i<24;i++)$('context-map').append(document.createElement('i'));[...$('context-map').children].forEach((el,i)=>{const v=c.context[i];el.style.background=v>=0?`rgba(181,206,125,${.12+Math.abs(v)*.8})`:`rgba(124,177,199,${.12+Math.abs(v)*.8})`;});
 const r=$('retina').getContext('2d'),retina=state.senses[selected].retina3d;r.clearRect(0,0,320,125);if(retina)retina.forEach((row,j)=>row.forEach((pixel,i)=>{r.fillStyle=`rgb(${pixel.slice(0,3).map(v=>Math.round(clamp(v,0,1)*255)).join(',')})`;r.fillRect(i*20+1,(4-j)*25+1,18,23);}));
 const key=state.journal.map(x=>x.id).join('|');if(key!==journalKey){journalKey=key;$('journal').replaceChildren();for(const e of [...state.journal].reverse()){const div=document.createElement('div');div.className='journal-entry';const t=document.createElement('time'),p=document.createElement('p');t.textContent=clock(e.time);p.textContent=e.text;div.append(t,p);$('journal').append(div);}}
 $('error-banner').style.display=state.error?'block':'none';$('error-banner').textContent=state.error||'';}
function resize(){const r=canvas.getBoundingClientRect();renderer.setSize(r.width,r.height,false);camera.aspect=r.width/r.height;camera.updateProjectionMatrix();}new ResizeObserver(resize).observe(canvas);
function frame(){requestAnimationFrame(frame);for(const m of [...objects.values(),...bodies.values()])if(m.userData.target){m.position.lerp(m.userData.target,.45);m.quaternion.slerp(m.userData.rotation,.45);}const b=bodies.get(selected);if(b){selectRing.position.copy(b.position);selectRing.position.z+=.004;if(cameraMode==='follow'){const offset=new THREE.Vector3(-1.1,-1.2,.85);camera.position.lerp(b.position.clone().add(offset),.08);camera.lookAt(b.position);}else if(cameraMode==='eyes'){camera.position.copy(b.position).add(new THREE.Vector3(.13,0,.04).applyQuaternion(b.quaternion));camera.up.set(0,0,1);camera.lookAt(b.position.clone().add(new THREE.Vector3(1,0,.04).applyQuaternion(b.quaternion)));}}
 if(cameraMode==='overview')controls.update();renderer.render(scene,camera);}frame();
let retry=0;function connect(){const ws=new WebSocket(`${location.protocol==='https:'?'wss':'ws'}://${location.host}/ws`);ws.onopen=()=>{retry=0;$('connection').textContent='● live';$('connection').classList.add('online');};ws.onmessage=e=>{const data=JSON.parse(e.data);if(!data.bodies){$('anatomy').textContent=data.error||'Starting…';return;}state=data;lastReceived=performance.now();$('anatomy').textContent=`MaleCNS v1.0 · ${data.anatomy.neurons.toLocaleString()} neurons · full brain + cord`;updateScene();updatePanel();};ws.onclose=()=>{$('connection').textContent='reconnecting';$('connection').classList.remove('online');setTimeout(connect,Math.min(5000,500+retry++*700));};ws.onerror=()=>ws.close();}connect();
